name: AppMon Resources Cache Purge & Warmup

on:
  push:
    branches:
      - main
    paths:
      - 'assets/**'
  workflow_dispatch:

jobs:
  purge-and-warmup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7

      - name: Run jsDelivr Purge & Warmup
        run: |
          PROPERTIES_FILE="appmon-demo/app/config/appmon/appmon-assets-prod.properties"
          
          if [ -f "$PROPERTIES_FILE" ]; then
            base_url=$(grep "^url=" "$PROPERTIES_FILE" | cut -d'=' -f2- | tr -d '\r\n ')
            version=$(grep "^cacheBustingVersion=" "$PROPERTIES_FILE" | cut -d'=' -f2- | tr -d '\r\n ')
          else
            echo "Properties file not found!"
            exit 1
          fi
          
          cdnPath=$(echo "$base_url" | sed -e "s|https\?://cdn.jsdelivr.net/||")
          targetDir=$(echo "$cdnPath" | sed -e "s|gh/[^/]\+/[^/]\+@\?[^/]\+/||")
          
          echo "Target directory: $targetDir"
          echo "Target CDN Path: $cdnPath"
          echo "Cache Version: $version"
          
          # Find all files under assets/$path_part and send Purge & Warmup requests
          find "$targetDir" -type f ! -path '*/.*' | while read -r file; do
            # 1. jsDelivr Purge API call
            purge_url="https://purge.jsdelivr.net/gh/aspectran/aspectow@main/${file}"
            echo -n "Purging jsDelivr Cache: $purge_url -> "
            purge_status=$(curl -s -o /dev/null -w "%{http_code}" "$purge_url")
            echo "Status: $purge_status"
            
            sleep 0.5
            
            # 2. jsDelivr Warmup call
            jsdelivr_url="https://cdn.jsdelivr.net/gh/aspectran/aspectow@main/${file}?v=${version}"
            echo -n "Warming up jsDelivr: $jsdelivr_url -> "
            warmup_status=$(curl -I -s -o /dev/null -w "%{http_code}" "$jsdelivr_url")
            echo "Status: $warmup_status"
            
            echo "------------------------------------------------"
          done
